export const ICON_MAP: Record<string, string> = {
  home:                       'home',
  upload:                     'upload',
  receipt_long:               'receipt',
  bar_chart:                  'chart-bar',
  storefront:                 'store',
  description:                'file-document',
  repeat:                     'repeat',
  account_balance_wallet:     'wallet',
  savings:                    'piggy-bank',
  settings:                   'cog',
  credit_card:                'credit-card',
  category:                   'shape',
  account_balance:            'bank',
  arrow_upward:               'arrow-up',
  arrow_downward:             'arrow-down',
  trending_up:                'trending-up',
  trending_down:              'trending-down',
  payments:                   'cash',
  shopping_bag:               'shopping',
  label:                      'label',
  label_off:                  'label-off',
  close:                      'close',
  add:                        'plus',
  add_circle:                 'plus-circle',
  add_card:                   'credit-card-plus',
  search:                     'magnify',
  search_off:                 'magnify-remove',
  chevron_left:               'chevron-left',
  chevron_right:              'chevron-right',
  expand_more:                'chevron-down',
  expand_less:                'chevron-up',
  check:                      'check',
  check_circle:               'check-circle',
  delete:                     'delete',
  replay:                     'replay',
  refresh:                    'refresh',
  smart_toy:                  'robot',
  logout:                     'logout',
  person:                     'account',
  download:                   'download',
  drive_file_rename_outline:  'rename-box',
  auto_fix_high:              'auto-fix',
  star:                       'star',
  emoji_events:               'trophy',
  keyboard_arrow_down:        'chevron-down',
  date_range:                 'calendar-range',
  calendar_view_month:        'calendar-month',
  table_view:                 'table',
  picture_as_pdf:             'file-pdf-box',
  summarize:                  'text-box-check',
  info:                       'information',
  warning:                    'alert',
  error:                      'alert-circle',
  light_mode:                 'white-balance-sunny',
  dark_mode:                  'moon-waning-crescent',
  cloud_upload:               'cloud-upload',
  notifications_active:       'bell-ring',
  history:                    'history',
  edit:                       'pencil',
  edit_off:                   'pencil-off',
  colorize:                   'eyedropper',
  rule:                       'list-status',
  schedule:                   'clock-outline',
  lock:                       'lock',
  upgrade:                    'arrow-up-circle',
  shopping_cart:              'cart',
  restaurant:                 'food',
  directions_car:             'car',
  bolt:                       'lightning-bolt',
  favorite:                   'heart',
  movie:                      'movie',
  south:                      'arrow-down',
  sync_alt:                   'sync',
  autorenew:                  'autorenew',
  flight:                     'airplane',
  local_hospital:             'hospital-box',
  school:                     'school',
  fitness_center:             'dumbbell',
  coffee:                     'coffee',
  local_gas_station:          'gas-station',
  phone:                      'phone',
  wifi:                       'wifi',
  tv:                         'television',
  beach_access:               'beach',
  pets:                       'paw',
  celebration:                'party-popper',
  build:                      'wrench',
  more_horiz:                 'dots-horizontal',
  menu:                       'menu',
  chevron_right_alt:          'arrow-right',
  attach_money:               'currency-usd',
  currency_exchange:          'currency-usd-circle',
  local_atm:                  'bank-transfer',
};

export const PRESET_ICONS = [
  'shopping_cart', 'restaurant', 'directions_car', 'bolt', 'favorite',
  'movie', 'shopping_bag', 'south', 'sync_alt', 'autorenew', 'label',
  'home', 'flight', 'local_hospital', 'school', 'fitness_center',
  'coffee', 'local_gas_station', 'phone', 'wifi', 'tv', 'savings',
  'credit_card', 'receipt_long', 'attach_money', 'currency_exchange',
  'bar_chart', 'beach_access', 'pets', 'celebration', 'build', 'more_horiz',
];

export const PRESET_COLORS = [
  "#10b981", "#ef4444", "#f59e0b", "#3b82f6",
  "#8b5cf6", "#ec4899", "#14b8a6", "#f97316",
  "#6b7280",
];

export const BUDGET_PRESET_COLORS = [
  "#ef4444", "#f97316", "#f59e0b", "#eab308",
  "#84cc16", "#22c55e", "#10b981", "#14b8a6",
  "#06b6d4", "#3b82f6", "#6366f1", "#8b5cf6",
  "#a855f7", "#ec4899", "#f43f5e", "#64748b",
];
